// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY50eJxHZ0TwNXLqTd-Z7ErhVQzLm6A7w',
    appId: '1:990121872415:web:daaea57fc761eefcb9192a',
    messagingSenderId: '990121872415',
    projectId: 'firstproject-25733',
    authDomain: 'firstproject-25733.firebaseapp.com',
    storageBucket: 'firstproject-25733.appspot.com',
    measurementId: 'G-DW3DTVYPT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAmCuLTGLc0J8-U-dGqELEfWroma57dQY',
    appId: '1:990121872415:android:73be7c5f078d44e0b9192a',
    messagingSenderId: '990121872415',
    projectId: 'firstproject-25733',
    storageBucket: 'firstproject-25733.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV4CNNoUyHpuriBUz9f69jx1aIMx5_bj4',
    appId: '1:990121872415:ios:1f5b61d38a9f7f13b9192a',
    messagingSenderId: '990121872415',
    projectId: 'firstproject-25733',
    storageBucket: 'firstproject-25733.appspot.com',
    iosBundleId: 'com.example.firstproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV4CNNoUyHpuriBUz9f69jx1aIMx5_bj4',
    appId: '1:990121872415:ios:1f5b61d38a9f7f13b9192a',
    messagingSenderId: '990121872415',
    projectId: 'firstproject-25733',
    storageBucket: 'firstproject-25733.appspot.com',
    iosBundleId: 'com.example.firstproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY50eJxHZ0TwNXLqTd-Z7ErhVQzLm6A7w',
    appId: '1:990121872415:web:32467cc0eec400fbb9192a',
    messagingSenderId: '990121872415',
    projectId: 'firstproject-25733',
    authDomain: 'firstproject-25733.firebaseapp.com',
    storageBucket: 'firstproject-25733.appspot.com',
    measurementId: 'G-TQ8N42V03P',
  );

}